### ISSUE TITLE
Another Feature Request: Pre Deploy Task?

### ISSUE THREAD

**Issue by asadsahi** [mkloubert/vs-deploy#12]
Is there a way to trigger a pre deploy task e.g If in an asp.net core application. we want to do publishing using 'dotnet publish' before deploy starts?

**Comment by mkloubert** [comment]
**Implemented since Version 3.20.0 and available now!**

```json
{
    "deploy": {
        "targets": [
            {
                "type": "ftp",
                "name": "My FTP folder",
                "description": "A FTP folder",
                "dir": "/my_package_files",
                "host": "localhost", "port": 21,
                "user": "anonymous", "password": "",

                "beforeDeploy": [
                    {
                        "target": "dotnet publish"
                    }
                ]
            }
        ]
    }
}
```

Have a look at the [wiki](https://github.com/mkloubert/vs-deploy/wiki#beforedeploy-) to get more detailed information.

Btw: **There is also '[deployed](https://github.com/mkloubert/vs-deploy/wiki#deployed-)' to invoke things AFTER successful deployment.** E.g. for things like "cache resets".

**Comment by asadsahi** [comment]
Thanks @mkloubert 

Upgraded to 3.20.0 and getting this:

![image](https://cloud.githubusercontent.com/assets/3470892/21351158/feb992bc-c6b2-11e6-8052-a56c54f5d80c.png)

**Comment by mkloubert** [comment]
Sorry, my mistake!

**Should be fixed since version 3.21.0 and available now.**

Try this:

```json
{
    "deploy": {
        "targets": [
            {
                /// ...

                "beforeDeploy": [
                    {
                        "target": "dotnet",
                        "arguments": [ "publish" ]
                    }
                ]
            }
        ]
    }
}
```

**Comment by asadsahi** [comment]
@mkloubert thanks for quick response.

I think it doesn't work quite well. if I delete bin folder to start of with i.e there are no files, then it fails with this warning. 
![image](https://cloud.githubusercontent.com/assets/3470892/21352932/9e9a1146-c6bb-11e6-8978-a2f4d10526d5.png)


If I run **dotnet publish** command from an external window. i.e files are already created in publish folder, then running deploy opens the command promp, then exited quickly and starts ftp.

I don't see publish happening.

**Comment by mkloubert** [comment]
**Should be fixed since version 3.21.1.**

The file list was not updated after tasks have been executed.

**Comment by asadsahi** [comment]
@mkloubert still getting same warning "**There are no files to deploy!**"

**Comment by mkloubert** [comment]
**Fixed since version 3.23.0 which is now available!**

![issue-12-fix-demo](https://cloud.githubusercontent.com/assets/4951215/21361503/968e129e-c6e4-11e6-974f-673f04aed643.gif)

This problem was that

* the path of `dotnet` executable has to be absolute
* `dotnet` has to be invoked from your workspace root (in the past this was the directory of VS Code)

That means you simply have to update the `settings.json` the following way:

```json
{
    "deploy": {
        "targets": [
            {
                /// ...

                "beforeDeploy": [
                    {
                        "target": "C:/Program Files/dotnet/dotnet.exe",
                        "arguments": [ "publish" ]
                    }
                ]
            }
        ]
    }
}
```

**Comment by asadsahi** [comment]
Awesome. Thanks @mkloubert . Worked well.
