### ISSUE TITLE
"Click here to cancel" is not working

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#22]
When deploying (using sftp), the "Deploying..." text is shown in the status bar but clicking on it does not cancel / stop the deployment.

**Comment by mkloubert** [comment]
**Should be fixed since version 4.18.0.**

**Comment by unional** [comment]
Just tested, still not working. When it is in "Deploying..", clicking on it doesn't work.

**Comment by mkloubert** [comment]
I could not reproduce it by 100%, but I have a theory:

The problem could be that SFTP operations may take some time, so it could look like it does not cancel.

While these operations are in progress I currently have no chance to cancel these operations (or do updates on the GUI), so it may take a while until the next operation checks when a cancellation has been requested.

I hope that this works much better with the improved speed of [SFTP uploads](https://github.com/mkloubert/vs-deploy/issues/24) now.

**Comment by unional** [comment]
With the new version, I am able to cancel it once by pressing it many times, but other times no.

When the tooltips updates, do you reattach the click event? Or maybe the tooltips is blocking the click event?

**Comment by mkloubert** [comment]
**I have released a new version 5.0.**

I refactored (and hope to improve) the concept of cancelling deployments.

Now I am using event based cancellations instead of VSCode global commands, which might be a better choice.

You should also be able to see if a deployment is cancelling ('Cancelling...' caption/tooltip appears) immediately.
