### ISSUE TITLE
Allow to ignore folder and files for FTP/SFTP deploy.

### ISSUE THREAD

**Issue by Shababsoft** [mkloubert/vs-deploy#57]
Please can you add a functionality that ignores files and folders during deployment.

`"ignore": [
        "\\.vscode",
        "\\.git",
        "\\*.sublime-project", 
        "\\*.sublime-workspace", 
        "sftp-config.json",
        "sftp-settings.json", 
        "\\.DS_Store", "Thumbs.db", "desktop.ini",
        "\\.buildpath", "\\.settings", "\\.project", "\\.idea"
    ]`

**Comment by mkloubert** [comment]
@Shababsoft 

I have released version 8.6.0 with a new (optional) `ignore` setting:

```json
{
    "deploy": {
        "ignore": [
            ".vscode",
            ".git",
            "/**/*.sublime-project",
            "/**/*.sublime-workspace",
            "sftp-config.json",
            "sftp-settings.json",
            ".DS_Store",
            "Thumbs.db",
            "desktop.ini",
            ".buildpath",
            ".settings",
            ".project",
            ".idea"
        ]
    }
}
```

This files will be ignored, even if you try to "force" to deploy them by using `Deploy: Deploy current file / folder` command or something else.

If you want to deploy a [package](https://github.com/mkloubert/vs-deploy/wiki#packages-), all files of it, that do match the upper list, will be removed from deployment.

You also can define files to `exclude` inside a package:

```json
{
    "deploy": {
        "packages": [
            {
                "name": "My project",

                "exclude": [
                    "/**/*.less",
                    "/**/*.ts",
                    "/**/*.pug"
                ]
            }
        ]
    }
}
```

BUT: `exclude` has NOT the same strict meaning as `ignore` here! In that case you can still deploy single files even they are part of the exclude list of a package.

**Comment by hushedmo** [comment]
@mkloubert awesome tool for VS code! I tried to ignore some files (e.g., `.vscode` folder) with `ignore` setting, but still got the error while pull or deploy, please check the below screenshot.
![image](https://cloud.githubusercontent.com/assets/28752965/26150642/e1f2eb8a-3b31-11e7-9543-04d12c69c3ef.png)
The version of Deploy is 9.1.1. Is there anything I missed? Any help would be appreciated :)

**Comment by mkloubert** [comment]
@hushedmo 

**This should be fixed since version 9.2.0.**

**Comment by hushedmo** [comment]
@mkloubert thanks for the update. Just upgrade to the latest 9.4.0, but still get the error. The ignore files will be deployed or pulled. Would you please have a check? Thanks!

**Comment by mkloubert** [comment]
@hushedmo 

It is a similar problem as issue #67.

Try to use `/.vscode/**/*` and `/.git/**/*` for the directory patterns instead.

**Comment by hushedmo** [comment]
@mkloubert Yes, it works like a charm. Thanks!

**Comment by 3zzy** [comment]
I'm also trying to get this work but keep getting:

`Could not deploy '/.vscode/settings.json' to 'Work' on save: TypeError: Cannot read property 'once' of null`

This is my config:

```
{
    "deploy": {
        "showWarningIfIgnored": false,
        "fastCheckOnSave" : true,
        "fastCheckForIgnores": true,
        "ignore": [
            "/.vscode/**/*",
            "/.git/**/*",
            "/**/*.sublime-project",
            "/**/*.sublime-workspace",
            "sftp-config.json",
            "sftp-settings.json",
            ".DS_Store",
            "Thumbs.db",
            "desktop.ini",
            ".buildpath",
            ".settings",
            ".project",
            ".idea"
        ],
        "targets": [
            {
                "type": "sftp",
                "name": "Work",
                "description": "Dev Server",
                "host": "dev", 
                "port": 22,
                "user": "xx",
                "privateKey": "/Users/myusername/.ssh/id_rsa",


                "checkBeforeDeploy": true,

                "mappings": [
                    {
                        "target": "/home/myusername/public_html/project-name"
                    }
                ]
            }
        ],
        "packages": [
            {
                "name": "foo",
                "description": "bar baz",
                "exclude": [],
                "deployOnSave": true
            }
        ]
    }
}
```

**Comment by mkloubert** [comment]
@3zzy 

Does the debug console (`CTRL + SHIFT + Y`) "say" something?

**Comment by mkloubert** [comment]
@3zzy 

On the other hand I see that `/.vscode/settings.json` is part of your ignore list.

I think you should check you [minimatch](https://github.com/isaacs/minimatch) patterns. Maybe removing leading `/` can help.

**Comment by frogydiak** [comment]
Using ignore or exclude seems to be not working, it will still deploy the file in my case via SFTP. I am deploying using the context menu (mouse right click).

**Update:**
Instead of a single asterisk use 2, `".vscode/**"` or `**.json`. But how do you denote root folder? For example, I only want to ignore composer.json in the root folder of the project?

**Comment by wangg12** [comment]
@frogydiak Have you figured out how to ignore files or directories in the root folder of the project?

**Comment by notrealdev** [comment]
> @mkloubert

Hi, what is theme name?

**Comment by frogydiak** [comment]
@wangg12 no, I have not and I forgot which project I am playing with this LOL! but based on the sample above you can do `"/.vscode/**/*"` so I guess you can try that pattern.
